import = [
    "~/.config/alacritty/alacritty.shell.toml",
]

[debug]
log_level = "Debug"
print_events = false

[scrolling]
history = 100000
multiplier = 3

[font.normal]
family = "FiraCode Nerd Font Mono"

[window.padding]
x = 16
y = 16

[window]
startup_mode = "Fullscreen"