#!/usr/bin/env bash

set -e

# Check if no arguments are passed
if [ $# -eq 0 ]; then
    echo "Usage:"
    echo "  ./install mac17         Setup MacBook Pro 2017"
    echo "  ./install mac23         Setup MacBook Pro 2023"
    echo "  ./install endeavour     Setup EndeavourOS"
    exit 1
fi

# Validate arguments
case "$1" in
    mac17|mac23|endeavour) ;;
    *)
        echo "Usage:"
        echo "  ./install mac17         Setup MacBook Pro 2017"
        echo "  ./install mac23         Setup MacBook Pro 2023"
        echo "  ./install endeavour     Setup EndeavourOS"
        exit 1
        ;;
esac

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

if [[ "$1" == mac* ]]; then
    sudo echo
    # NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    PATH=/opt/homebrew/bin:/usr/local/bin:~/.config/composer/vendor/bin:$PATH \
    "${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir dotbot-brew -v -c "mac.conf.yaml"

    if [[ "$1" == mac17 ]]; then
        CONFIG_FILE="mac17.conf.yaml"
    elif [[ "$1" == mac23 ]]; then
        CONFIG_FILE="mac23.conf.yaml"
    fi

    PATH=/opt/homebrew/bin:/usr/local/bin:~/.config/composer/vendor/bin:$PATH \
    "${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir dotbot-brew -v -c "${CONFIG_FILE}"
elif [[ "$1" == "endeavour" ]]; then
    "${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" -p dotbot-yay/yay.py -c "endeavour.conf.yaml"
fi
