# ----------------------------------- PATH ----------------------------------- #

path=(
	$HOME/.config/composer/vendor/bin(N-/)
	$HOME/bin(N-/)
	$path
)

# macOS-specific paths
if [[ "$(uname)" == "Darwin" ]]; then
    if [[ "$(uname -m)" == "x86_64" ]]; then
        path=(
            /usr/local/bin(N-/)                  # Intel-specific Homebrew
            $path
        )
    elif [[ "$(uname -m)" == "arm64" ]]; then
        path=(
            /opt/homebrew/bin(N-/)
            $path
        )
    fi
fi

# Linux-specific paths
if [[ "$(uname)" == "Linux" ]]; then
    # path=(
    #     $path
    # )
fi

# Ensure unique and ordered paths
path=(${(u)path})

export PATH

# ----------------------------------- FPATH ---------------------------------- #

fpath=(
    $HOME/.dotfiles/zsh-completions/src
	$fpath
)

# macOS-specific fpaths
if [[ "$(uname)" == "Darwin" ]]; then
    if [[ "$(uname -m)" == "x86_64" ]]; then
        fpath=(
            $fpath
        )
    elif [[ "$(uname -m)" == "arm64" ]]; then
        fpath=(
            $fpath
        )
    fi
fi

# Linux-specific fpaths
if [[ "$(uname)" == "Linux" ]]; then
    # fpath=(
    #     $fpath
    # )
fi

# Ensure unique and ordered fpaths
fpath=(${(u)fpath})

export FPATH