# ----------------------------------- PATH ----------------------------------- #

path=(
	$HOME/bin(N-/)
	$path
)

# macOS-specific paths
# if [[ "$(uname)" == "Darwin" ]]; then
#     if [[ "$(uname -m)" == "x86_64" ]]; then
#         path=(
#             /usr/local/bin(N-/)                  # Intel-specific Homebrew
#             $path
#         )
#     elif [[ "$(uname -m)" == "arm64" ]]; then
#         path=(
#             /opt/homebrew/bin(N-/)
#             $path
#         )
#     fi
# fi

# Linux-specific paths
# if [[ "$(uname)" == "Linux" ]]; then
#     path=(
#         $path
#     )
# fi

# ------------------------ Setting up brew environment ----------------------- #

if [[ "$(uname)" == "Darwin" ]]; then
    if [[ "$(uname -m)" == "x86_64" ]]; then
        eval  "$(/usr/local/bin/brew shellenv)"
    elif [[ "$(uname -m)" == "arm64" ]]; then
        eval  "$(/opt/homebrew/bin/brew shellenv)"
    fi
fi

# ----------------------------------- FPATH ---------------------------------- #

fpath=(
    $HOME/.dotfiles/zsh-completions/src
	$fpath
)

# macOS-specific fpaths
# if [[ "$(uname)" == "Darwin" ]]; then
#     if [[ "$(uname -m)" == "x86_64" ]]; then
#         fpath=(
#             $fpath
#         )
#     elif [[ "$(uname -m)" == "arm64" ]]; then
#         fpath=(
#             $fpath
#         )
#     fi
# fi

# Linux-specific fpaths
# if [[ "$(uname)" == "Linux" ]]; then
#     fpath=(
#         $fpath
#     )
# fi

# ------------------------- Exporting PATH and FPATH ------------------------- #

# Ensure unique and ordered paths
path=(${(u)path})

export PATH

# Ensure unique and ordered fpaths
fpath=(${(u)fpath})

export FPATH