# PATH management
path=(
	$HOME/.config/composer/vendor/bin(N-/)
	$HOME/bin(N-/)
	$path
)

# macOS-specific paths
if [[ "$(uname)" == "Darwin" ]]; then
    if [[ "$(uname -m)" == "x86_64" ]]; then
        path=(
            /usr/local/bin(N-/)                  # Intel-specific Homebrew
            $path
        )
    elif [[ "$(uname -m)" == "arm64" ]]; then
        path=(
            /opt/homebrew/bin(N-/)    
            $path           # M1-specific Homebrew
        )
    fi
fi

# Linux-specific paths
if [[ "$(uname)" == "Linux" ]]; then
    # path=(
    #     $path
    # )
fi

# Ensure unique and ordered paths
path=(${(u)path})

# Export PATH
export PATH