# Activating completions, needed for oh-my-zsh plugins
autoload -Uz compinit
compinit

# variables
source $HOME/.config/zsh/variables.zsh

# aliases
source $HOME/.dotfiles/ohmyzsh/plugins/aliases/aliases.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/common-aliases/common-aliases.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/lib/git.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/git/git.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/rsync/rsync.plugin.zsh
source $HOME/.config/zsh/aliases.zsh

if command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env --use-on-cd --shell zsh)"
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ "$(uname)" == "Darwin" ]]; then
    source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
fi

if [[ "$(uname)" == "Linux" ]]; then
    source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
