# Activating completions
ZSH_COMPDUMP="$HOME/.cache/zsh/zcompcache"

[[ -d $ZSH_COMPDUMP ]] || mkdir -p $ZSH_COMPDUMP

_comp_files=($ZSH_COMPDUMP/zcompdump(Nm-20))

if (( $#_comp_files )); then
    autoload -Uz compinit -C -d "$ZSH_COMPDUMP/.zcompdump-${ZSH_VERSION}"
else
    autoload -Uz compinit -d "$ZSH_COMPDUMP/.zcompdump-${ZSH_VERSION}"
fi

compinit

# variables
source $HOME/.config/zsh/variables.zsh

# omz plugins
source $HOME/.dotfiles/ohmyzsh/plugins/aliases/aliases.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/common-aliases/common-aliases.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/composer/composer.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/docker/docker.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/docker-compose/docker-compose.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/lib/git.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/git/git.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/gnu-utils/gnu-utils.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/laravel/laravel.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/rsync/rsync.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/ssh/ssh.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/sudo/sudo.plugin.zsh
source $HOME/.dotfiles/ohmyzsh/plugins/yarn/yarn.plugin.zsh

# macOS-specific omz plugins
if [[ "$(uname)" == "Darwin" ]]; then
    source $HOME/.dotfiles/ohmyzsh/plugins/brew/brew.plugin.zsh

    # if [[ "$(uname -m)" == "x86_64" ]]; then
       
    # elif [[ "$(uname -m)" == "arm64" ]]; then
        
    # fi
fi

# Linux-specific paths
# if [[ "$(uname)" == "Linux" ]]; then

# fi

# aliases
source $HOME/.config/zsh/aliases.zsh

# autosuggestions
source $HOME/.dotfiles/zsh-autosuggestions/zsh-autosuggestions.zsh

# setting history options
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY_TIME
setopt EXTENDED_HISTORY

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ "$(uname)" == "Darwin" ]]; then
    source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
fi

if [[ "$(uname)" == "Linux" ]]; then
    source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Added by Windsurf
export PATH="/Users/marcoluzi/.codeium/windsurf/bin:$PATH"
