windowrulev2 = fullscreen,class:^steam_app\d+$
windowrulev2 = monitor 1,class:^steam_app_\d+$
windowrulev2 = workspace 10,class:^steam_app_\d+$
workspace = 10, border:false, rounding:false

windowrulev2 = float,class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2 = size 500 400,class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2 = move 2047 55,class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2 = noborder,class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2 = pin,class:^(org\.pulseaudio\.pavucontrol)$
